gantt
    title {{project_name}}
    dateFormat {{date_format}}
    
    section {{section1_name}}
    {{task1_1_name}} :{{task1_1_status}}, {{task1_1_id}}, {{task1_1_start}}, {{task1_1_duration}}
    {{task1_2_name}} :{{task1_2_status}}, {{task1_2_id}}, {{task1_2_start}}, {{task1_2_duration}}
    {{task1_3_name}} :{{task1_3_status}}, {{task1_3_id}}, {{task1_3_start}}, {{task1_3_duration}}
    
    section {{section2_name}}
    {{task2_1_name}} :{{task2_1_status}}, {{task2_1_id}}, {{task2_1_start}}, {{task2_1_duration}}
    {{task2_2_name}} :{{task2_2_status}}, {{task2_2_id}}, {{task2_2_start}}, {{task2_2_duration}}
    
    section {{section3_name}}
    {{task3_1_name}} :{{task3_1_status}}, {{task3_1_id}}, {{task3_1_start}}, {{task3_1_duration}}
    {{task3_2_name}} :{{task3_2_status}}, {{task3_2_id}}, {{task3_2_start}}, {{task3_2_duration}}

